version: '3.8'
services:
  postgres:
    container_name: ctf-postgres-container
    image: postgres:alpine
    environment:
      POSTGRES_DB: ctf_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ctf-postgres-volume:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - ctf-postgres-network
    restart: always

networks:
  ctf-postgres-network:
    driver: bridge

volumes:
  ctf-postgres-volume:
