version: '3.8'
services:
  postgres:
    container_name: ctf-postgres-container
    image: postgres:alpine
    environment:
      POSTGRES_DB: ctf_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ctf-postgres-volume:/data/postgres
    ports:
      - "5433:5432"
    restart: always

  minio:
    container_name: ctf-minio-container
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ctf-minio-volume:/minio
    ports:
      - "9090:9090"
      - "9000:9000"
    restart: always
    command: server ~/minio --console-address :9090

volumes:
  ctf-postgres-volume:
  ctf-minio-volume:
