spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ctf_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false
    locations: classpath:db/migration

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      access-token-expiration: 86400000 # a day
      refresh-token-expiration: 604800000 # 7 days

  time-zone: Z