spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ctf_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    operations-sorter: method
  override-with-generic-response: true

minio:
  bucket-name: tasks
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      access-token-expiration: 86400000 # a day
      refresh-token-expiration: 604800000 # 7 days

  time-zone: Z